$(function(){
    $('#main-container').hover(
        function(){
            $(this).find('.sub-container').addClass('sub-active');
        }
        ,function(){
            $(this).find('.sub-container').removeClass('sub-active');
        }
    );
});
